### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by lizixiaoboluo** [LLLogen/VSDcode#1]
Hi,
I'm having connectivity issues:
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.
How to solve it ?

**Comment by LLLogen** [comment]
> Hi, I'm having connectivity issues: ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on. How to solve it ?

Hi, could you provide the detailed error logs? I guess it's a network problem. You should make sure that your server could connect to the https://huggingface.co/, or you may manually download the related model weights.

**Comment by lizixiaoboluo** [comment]
> > Hi, I'm having connectivity issues: ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on. How to solve it ?
> 
> Hi, could you provide the detailed error logs? I guess it's a network problem. You should make sure that your server could connect to the https://huggingface.co/, or you may manually download the related model weights.

Traceback (most recent call last):
  File "VLModel/src/vsd.py", line 471, in <module>
    main_worker(args.local_rank, args)
  File "VLModel/src/vsd.py", line 410, in main_worker
    topk=args.train_topk,
  File "/home/VSDcode/VLModel/src/caption_data.py", line 694, in get_vsd_loader
    mode=mode)
  File "/home/VSDcode/VLModel/src/caption_data.py", line 380, in __init__
    args.backbone,)
  File "/home/.conda/envs/vsd/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1745, in from_pretrained
    use_auth_token=use_auth_token,
  File "/home/.conda/envs/vsd/lib/python3.7/site-packages/transformers/file_utils.py", line 1056, in cached_path
    local_files_only=local_files_only,
  File "/home/.conda/envs/vsd/lib/python3.7/site-packages/transformers/file_utils.py", line 1235, in get_from_cache
    "Connection error, and we cannot find the requested files in the cached path."
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.
It's a network problem. I use mirror to download, but I failed.

**Comment by LLLogen** [comment]
> > > Hi, I'm having connectivity issues: ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on. How to solve it ?
> > 
> > 
> > Hi, could you provide the detailed error logs? I guess it's a network problem. You should make sure that your server could connect to the https://huggingface.co/, or you may manually download the related model weights.
> 
> Traceback (most recent call last): File "VLModel/src/vsd.py", line 471, in main_worker(args.local_rank, args) File "VLModel/src/vsd.py", line 410, in main_worker topk=args.train_topk, File "/home/VSDcode/VLModel/src/caption_data.py", line 694, in get_vsd_loader mode=mode) File "/home/VSDcode/VLModel/src/caption_data.py", line 380, in **init** args.backbone,) File "/home/.conda/envs/vsd/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1745, in from_pretrained use_auth_token=use_auth_token, File "/home/.conda/envs/vsd/lib/python3.7/site-packages/transformers/file_utils.py", line 1056, in cached_path local_files_only=local_files_only, File "/home/.conda/envs/vsd/lib/python3.7/site-packages/transformers/file_utils.py", line 1235, in get_from_cache "Connection error, and we cannot find the requested files in the cached path." ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on. It's a network problem. I use mirror to download, but I failed.

Yes its a network problem. If the mirror doesn't work, you can manually download the model files from Huggingface or the mirror site to a path and change the "arg.backbone" in baseline.sh to that path.

**Comment by lizixiaoboluo** [comment]
Hi,
Traceback (most recent call last):
  File "VLModel/src/vsd.py", line 471, in <module>
    main_worker(args.local_rank, args)
  File "VLModel/src/vsd.py", line 410, in main_worker
    topk=args.train_topk,
  File "/home/VSDcode/VLModel/src/caption_data.py", line 694, in get_vsd_loader
    mode=mode)
  File "/home/VSDcode/VLModel/src/caption_data.py", line 418, in __init__
    for d in datum['captions']:
KeyError: 'captions'
 Where are the captions in train splits? I don‘t find it.

**Comment by LHLdragon579** [comment]
Hi, I'm having the same problem and have manually downloaded the model files from Huggingface to facebook/bart-base!
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/vocab.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fbb8f3cbe90>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: b947976e-2e84-4d84-bb87-2b45c557676e)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/vocab.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/vocab.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd9279c5f10>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 38a87fed-4017-4bfd-8a11-73ea05815e99)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/vocab.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/vocab.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa396fae110>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: b828b172-3540-4ede-ae41-2c1e8a2f6a9d)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/vocab.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/vocab.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f43d8bc30d0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 2b52e793-07ce-4804-b13a-1a1530f6adfe)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/vocab.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/merges.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fbb8f3fa210>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 1398dde4-11aa-45a6-8178-28eeb6c2b6f0)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/merges.txt
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/merges.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd9279f0290>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: a29574e4-0ca4-44db-aecc-e89b8de1e83f)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/merges.txt
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/merges.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa396fdd1d0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 3387258f-85c0-4116-8621-68f02bc726bf)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/merges.txt
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/merges.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f43d8bc3410>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: a83384ae-9041-4a77-9be0-5231459608f2)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/merges.txt
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/added_tokens.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fbb8f43ed50>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: f6997f01-8b49-4fc3-8ee8-572b756a7bb3)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/added_tokens.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/added_tokens.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd927a38150>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: d7265f1c-c8bf-405d-8f27-3a09b051d659)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/added_tokens.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/added_tokens.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa396fae590>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: ed5bb344-bc8c-432c-9184-db5c0eb22fb8)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/added_tokens.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/added_tokens.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f43d8bc3910>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: ee583548-bfa6-4b2b-b257-53bd853ba4ac)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/added_tokens.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/special_tokens_map.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fbb8f3fa190>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 4ab90cf7-b436-42be-9a83-ca75b98df6b8)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/special_tokens_map.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/special_tokens_map.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd9279f0090>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 164a516e-932d-48a3-8186-7a0d400278c3)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/special_tokens_map.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/special_tokens_map.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa396fdd310>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 5fb322ca-aaf0-4689-a45d-307deed321ff)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/special_tokens_map.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/special_tokens_map.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f43d00c0090>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: aa3b4036-188f-4623-a1ca-1fa517d27274)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/special_tokens_map.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fbb8f3fa290>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 6187d205-6e5d-4c43-b621-9b5260958116)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/tokenizer_config.json
Traceback (most recent call last):
  File "VLModel/src/caption_sp.py", line 516, in <module>
    main_worker(args.local_rank, args)
  File "VLModel/src/caption_sp.py", line 455, in main_worker
    topk=args.train_topk,
  File "/home/lhl/VSD-master/VLModel/src/caption_data.py", line 742, in get_sp_loader
    mode=mode)
  File "/home/lhl/VSD-master/VLModel/src/caption_data.py", line 394, in __init__
    do_lower_case=self.args.do_lower_case)
  File "/root/anaconda3/envs/vsd/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1810, in from_pretrained
    f"Can't load tokenizer for '{pretrained_model_name_or_path}'. If you were trying to load it from "
OSError: Can't load tokenizer for 'facebook/bart-base'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'facebook/bart-base' is the correct path to a directory containing all relevant files for a BartTokenizer tokenizer.
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd9279f0510>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 3609ada6-d59f-4896-9f6f-fd4d2c54a1f5)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/tokenizer_config.json
Traceback (most recent call last):
  File "VLModel/src/caption_sp.py", line 516, in <module>
    main_worker(args.local_rank, args)
  File "VLModel/src/caption_sp.py", line 455, in main_worker
    topk=args.train_topk,
  File "/home/lhl/VSD-master/VLModel/src/caption_data.py", line 742, in get_sp_loader
    mode=mode)
  File "/home/lhl/VSD-master/VLModel/src/caption_data.py", line 394, in __init__
    do_lower_case=self.args.do_lower_case)
  File "/root/anaconda3/envs/vsd/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1810, in from_pretrained
    f"Can't load tokenizer for '{pretrained_model_name_or_path}'. If you were trying to load it from "
OSError: Can't load tokenizer for 'facebook/bart-base'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'facebook/bart-base' is the correct path to a directory containing all relevant files for a BartTokenizer tokenizer.
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa396fdd490>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: f4137fa9-1780-49bb-9604-4c8a674cdcd4)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/tokenizer_config.json
Traceback (most recent call last):
  File "VLModel/src/caption_sp.py", line 516, in <module>
    main_worker(args.local_rank, args)
  File "VLModel/src/caption_sp.py", line 455, in main_worker
    topk=args.train_topk,
  File "/home/lhl/VSD-master/VLModel/src/caption_data.py", line 742, in get_sp_loader
    mode=mode)
  File "/home/lhl/VSD-master/VLModel/src/caption_data.py", line 394, in __init__
    do_lower_case=self.args.do_lower_case)
  File "/root/anaconda3/envs/vsd/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1810, in from_pretrained
    f"Can't load tokenizer for '{pretrained_model_name_or_path}'. If you were trying to load it from "'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/bart-base/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f43d00c07d0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 5f94d607-73ea-4e9b-8fd6-6de9736fe0e3)')' thrown while requesting HEAD https://huggingface.co/facebook/bart-base/resolve/main/tokenizer_config.json

OSError: Can't load tokenizer for 'facebook/bart-base'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'facebook/bart-base' is the correct path to a directory containing all relevant files for a BartTokenizer tokenizer.
Traceback (most recent call last):
  File "VLModel/src/caption_sp.py", line 516, in <module>
    main_worker(args.local_rank, args)
  File "VLModel/src/caption_sp.py", line 455, in main_worker
    topk=args.train_topk,
  File "/home/lhl/VSD-master/VLModel/src/caption_data.py", line 742, in get_sp_loader
    mode=mode)
  File "/home/lhl/VSD-master/VLModel/src/caption_data.py", line 394, in __init__
    do_lower_case=self.args.do_lower_case)
  File "/root/anaconda3/envs/vsd/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1810, in from_pretrained
    f"Can't load tokenizer for '{pretrained_model_name_or_path}'. If you were trying to load it from "
OSError: Can't load tokenizer for 'facebook/bart-base'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'facebook/bart-base' is the correct path to a directory containing all relevant files for a BartTokenizer tokenizer.
Traceback (most recent call last):
  File "/root/anaconda3/envs/vsd/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/vsd/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/vsd/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/root/anaconda3/envs/vsd/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/vsd/bin/python', '-u', 'VLModel/src/caption_sp.py', '--local_rank=3', '--distributed', '--multiGPU', '--train', 'train', '--valid', 'val', '--test', 'test', '--optim', 'adamw', '--warmup_ratio', '0.1', '--clip_grad_norm', '5', '--lr', '5e-5', '--epochs', '20', '--num_workers', '4', '--backbone', 'facebook/bart-base', '--output', 'snap/sp/baseline', '--load', 'snap/pretrain/VLBart/Epoch30', '--num_beams', '5', '--batch_size', '80', '--valid_batch_size', '100']' returned non-zero exit status 1.

**Comment by LLLogen** [comment]
> Hi, Traceback (most recent call last): File "VLModel/src/vsd.py", line 471, in main_worker(args.local_rank, args) File "VLModel/src/vsd.py", line 410, in main_worker topk=args.train_topk, File "/home/VSDcode/VLModel/src/caption_data.py", line 694, in get_vsd_loader mode=mode) File "/home/VSDcode/VLModel/src/caption_data.py", line 418, in **init** for d in datum['captions']: KeyError: 'captions' Where are the captions in train splits? I don‘t find it.

That's a typo, "captions" should be "description". Have updated now.
